apiVersion: v1
items:
- apiVersion: networking.k8s.io/v1
  kind: Ingress
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"name":"pacman","namespace":"pacman"},"spec":{"rules":[{"host":"pacman.local","http":{"paths":[{"backend":{"service":{"name":"pacman","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
    creationTimestamp: "2024-02-21T12:01:14Z"
    generation: 1
    name: pacman
    namespace: pacman
    resourceVersion: "30770"
    uid: 0d326399-b80a-418e-ae0b-fcb812840abf
  spec:
    ingressClassName: nginx
    rules:
    - host: pacman.local
      http:
        paths:
        - backend:
            service:
              name: pacman
              port:
                number: 80
          path: /
          pathType: Prefix
  status:
    loadBalancer:
      ingress:
      - ip: 192.168.49.2
kind: List
metadata:
